// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Srudent.proto

package com.zakl.proto;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zakl.protobuf.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string age = 2;</code>
   */
  java.lang.String getAge();
  /**
   * <code>string age = 2;</code>
   */
  com.google.protobuf.ByteString
      getAgeBytes();

  /**
   * <code>string city = 3;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 3;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
