// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Srudent.proto

package com.zakl.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zakl.protobuf.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.zakl.protobuf.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.zakl.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.zakl.protobuf.StudentResponse studentResponse = 1;</code>
   */
  com.zakl.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.zakl.protobuf.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.zakl.protobuf.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.zakl.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.zakl.protobuf.StudentResponse studentResponse = 1;</code>
   */
  com.zakl.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
